-- =====================================================================================
-- V1002__dev_questions_with_figures.sql — DEV / TEST ONLY
--   * 6 questions that use figures: diagrams in the question, images as options, and a
--     solution figure
--   * a free "Diagram Practice Test" in the free starter series (3 attempts allowed)
--
-- The figures are static SVGs in frontend/public/samples (generated by
-- frontend/scripts/generate-sample-figures.cjs). They are served at /samples/... by Vite in dev
-- and by nginx in Docker, so they work without MinIO. Real uploads through the question
-- editor go to S3/MinIO and store absolute URLs.
-- NOTE: JSON strings need "\\" for a literal backslash, so LaTeX \frac is written \\frac.
-- =====================================================================================

INSERT INTO questions (id, type, difficulty, language, exam_id, subject_id, chapter_id, topic_id,
                       content, correct_answer, default_marks, default_negative_marks, source, created_by)
VALUES
-- Physics: block on a smooth incline (figure + solution figure)
('14000000-0000-7000-8000-000000000051', 'SINGLE_CORRECT', 'EASY', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000001',
 '12000000-0000-7000-8000-000000000002', '13000000-0000-7000-8000-000000000003',
 '{"text": "A block of mass $m$ is released from rest on the smooth inclined plane shown in the figure. Its acceleration down the incline is (take $g = 10\\,\\text{m/s}^2$):",
   "images": [{"url": "/samples/incline.svg", "alt": "Block of mass m on a smooth incline making 30 degrees with the horizontal"}],
   "options": [{"id": "A", "text": "$5\\,\\text{m/s}^2$"}, {"id": "B", "text": "$10\\,\\text{m/s}^2$"},
               {"id": "C", "text": "$8.66\\,\\text{m/s}^2$"}, {"id": "D", "text": "$2.5\\,\\text{m/s}^2$"}],
   "solution": {"text": "Only gravity has a component along the smooth incline: $ma = mg\\sin\\theta$, so $a = g\\sin 30^\\circ = 10 \\times \\frac{1}{2} = 5\\,\\text{m/s}^2$. The normal force $mg\\cos\\theta$ balances the perpendicular component.",
                "images": [{"url": "/samples/incline-fbd.svg", "alt": "Free-body diagram showing N, mg and mg sin theta"}]}}',
 '{"options": ["A"]}', 4, 1, 'Sample (figure)', '00000000-0000-7000-8000-000000000002'),

-- Physics: distance from a velocity-time graph (numerical)
('14000000-0000-7000-8000-000000000052', 'NUMERICAL', 'MEDIUM', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000001',
 '12000000-0000-7000-8000-000000000001', '13000000-0000-7000-8000-000000000001',
 '{"text": "The velocity–time graph of a particle moving along a straight line is shown. The distance travelled by the particle (in m) in the first $10\\,\\text{s}$ is ______.",
   "images": [{"url": "/samples/vt-graph.svg", "alt": "Velocity-time graph rising from 0 to 20 m/s in 4 s, constant until 8 s, falling to 0 at 10 s"}],
   "solution": {"text": "Distance = area under the $v$–$t$ graph $= \\frac{1}{2}(4)(20) + (4)(20) + \\frac{1}{2}(2)(20) = 40 + 80 + 20 = 140\\,\\text{m}$."}}',
 '{"value": 140}', 4, 0, 'Sample (figure)', '00000000-0000-7000-8000-000000000002'),

-- Physics: projectile maximum height (figure)
('14000000-0000-7000-8000-000000000053', 'SINGLE_CORRECT', 'MEDIUM', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000001',
 '12000000-0000-7000-8000-000000000001', '13000000-0000-7000-8000-000000000002',
 '{"text": "A ball is projected from the ground as shown in the figure. The maximum height $H$ reached by the ball is:",
   "images": [{"url": "/samples/projectile.svg", "alt": "Projectile launched at 30 degrees with speed 20 m/s showing maximum height H and range R"}],
   "options": [{"id": "A", "text": "$5\\,\\text{m}$"}, {"id": "B", "text": "$10\\,\\text{m}$"},
               {"id": "C", "text": "$15\\,\\text{m}$"}, {"id": "D", "text": "$20\\,\\text{m}$"}],
   "solution": {"text": "$H = \\frac{u^2\\sin^2\\theta}{2g} = \\frac{(20)^2 (1/2)^2}{2 \\times 10} = \\frac{100}{20} = 5\\,\\text{m}$"}}',
 '{"options": ["A"]}', 4, 1, 'Sample (figure)', '00000000-0000-7000-8000-000000000002'),

-- Chemistry: images as the options
('14000000-0000-7000-8000-000000000054', 'SINGLE_CORRECT', 'MEDIUM', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000002',
 '12000000-0000-7000-8000-000000000004', '13000000-0000-7000-8000-000000000006',
 '{"text": "Which diagram correctly shows the shape of the $\\mathrm{NH_3}$ molecule?\n(A = central atom, X = bonded atom, yellow lobe = lone pair)",
   "options": [{"id": "A", "image": "/samples/shape-planar.svg"}, {"id": "B", "image": "/samples/shape-pyramidal.svg"},
               {"id": "C", "image": "/samples/shape-tetrahedral.svg"}, {"id": "D", "image": "/samples/shape-bent.svg"}],
   "solution": {"text": "N has 3 bond pairs and 1 lone pair (steric number 4, $sp^3$). The lone pair pushes the three N–H bonds down, giving a trigonal pyramidal shape with bond angle $\\approx 107^\\circ$. (Option 1 is trigonal planar like $\\mathrm{BF_3}$, option 3 is tetrahedral like $\\mathrm{CH_4}$, option 4 is bent like $\\mathrm{H_2O}$.)"}}',
 '{"options": ["B"]}', 4, 1, 'Sample (figure)', '00000000-0000-7000-8000-000000000002'),

-- Chemistry: hydrogen energy-level diagram
('14000000-0000-7000-8000-000000000055', 'SINGLE_CORRECT', 'EASY', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000002',
 '12000000-0000-7000-8000-000000000003', '13000000-0000-7000-8000-000000000004',
 '{"text": "In the energy-level diagram of the hydrogen atom shown, the photon emitted in the marked transition belongs to the:",
   "images": [{"url": "/samples/energy-levels.svg", "alt": "Hydrogen energy levels n = 1 to infinity with an arrow from n = 3 down to n = 2"}],
   "options": [{"id": "A", "text": "Lyman series"}, {"id": "B", "text": "Balmer series"},
               {"id": "C", "text": "Paschen series"}, {"id": "D", "text": "Brackett series"}],
   "solution": {"text": "Transitions that end on $n = 2$ form the Balmer series. Here $\\Delta E = -1.51 - (-3.40) = 1.89\\,\\text{eV}$, so $\\lambda = \\frac{1240}{1.89} \\approx 656\\,\\text{nm}$ (the red H-$\\alpha$ line)."}}',
 '{"options": ["B"]}', 4, 1, 'Sample (figure)', '00000000-0000-7000-8000-000000000002'),

-- Mathematics: read the roots from a graph (numerical)
('14000000-0000-7000-8000-000000000056', 'NUMERICAL', 'MEDIUM', 'EN',
 '10000000-0000-7000-8000-000000000001', '11000000-0000-7000-8000-000000000003',
 '12000000-0000-7000-8000-000000000006', '13000000-0000-7000-8000-000000000009',
 '{"text": "The graph of $y = x^2 + bx + c$ is shown. It cuts the $x$-axis at the two marked points. The value of $b + c$ is ______.",
   "images": [{"url": "/samples/parabola.svg", "alt": "Upward parabola cutting the x-axis at x = 2 and x = 3"}],
   "solution": {"text": "The roots are $2$ and $3$, so $y = (x-2)(x-3) = x^2 - 5x + 6$. Hence $b = -5$, $c = 6$ and $b + c = 1$."}}',
 '{"value": 1}', 4, 0, 'Sample (figure)', '00000000-0000-7000-8000-000000000002');

INSERT INTO question_tags (question_id, tag) VALUES
    ('14000000-0000-7000-8000-000000000051', 'diagram'),
    ('14000000-0000-7000-8000-000000000052', 'diagram'),
    ('14000000-0000-7000-8000-000000000052', 'graph'),
    ('14000000-0000-7000-8000-000000000053', 'diagram'),
    ('14000000-0000-7000-8000-000000000054', 'diagram'),
    ('14000000-0000-7000-8000-000000000054', 'image-options'),
    ('14000000-0000-7000-8000-000000000055', 'diagram'),
    ('14000000-0000-7000-8000-000000000056', 'graph');

-- A free test in the starter series, so the demo student can attempt these right away.
INSERT INTO tests (id, series_id, exam_id, title, description, instructions, pattern, duration_minutes,
                   total_marks, total_questions, status, is_free, max_attempts, display_order, created_by)
VALUES ('16000000-0000-7000-8000-000000000005', '15000000-0000-7000-8000-000000000001',
        '10000000-0000-7000-8000-000000000001', 'Diagram Practice Test (figures & graphs)',
        'Six questions built around diagrams, graphs and picture options.',
        E'1. The test is of 20 minutes duration.\n2. Single-correct: +4 for correct, -1 for incorrect.\n3. Numerical: +4 for correct, no negative marking.\n4. Study each figure carefully. Figures are not always to scale.',
        'CUSTOM', 20, 24, 6, 'PUBLISHED', TRUE, 3, 2, '00000000-0000-7000-8000-000000000001');

INSERT INTO test_sections (id, test_id, subject_id, name, display_order) VALUES
    ('17000000-0000-7000-8000-000000000051', '16000000-0000-7000-8000-000000000005', '11000000-0000-7000-8000-000000000001', 'Physics',     1),
    ('17000000-0000-7000-8000-000000000052', '16000000-0000-7000-8000-000000000005', '11000000-0000-7000-8000-000000000002', 'Chemistry',   2),
    ('17000000-0000-7000-8000-000000000053', '16000000-0000-7000-8000-000000000005', '11000000-0000-7000-8000-000000000003', 'Mathematics', 3);

INSERT INTO test_questions (id, test_id, section_id, question_id, display_order, marks, negative_marks, partial_marking) VALUES
    ('18000000-0000-7000-8000-000000000051', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000051', '14000000-0000-7000-8000-000000000051', 1, 4, 1, FALSE),
    ('18000000-0000-7000-8000-000000000052', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000051', '14000000-0000-7000-8000-000000000052', 2, 4, 0, FALSE),
    ('18000000-0000-7000-8000-000000000053', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000051', '14000000-0000-7000-8000-000000000053', 3, 4, 1, FALSE),
    ('18000000-0000-7000-8000-000000000054', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000052', '14000000-0000-7000-8000-000000000054', 1, 4, 1, FALSE),
    ('18000000-0000-7000-8000-000000000055', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000052', '14000000-0000-7000-8000-000000000055', 2, 4, 1, FALSE),
    ('18000000-0000-7000-8000-000000000056', '16000000-0000-7000-8000-000000000005', '17000000-0000-7000-8000-000000000053', '14000000-0000-7000-8000-000000000056', 1, 4, 0, FALSE);
