#!/usr/bin/env bash
# Runs ON the server (run-deploy.cmd copies it there and starts it).
# Usage: bash deploy.sh <public-ip>
# First run: creates ~/examprep/.env with random secrets (never overwritten afterwards).
# Every run: pulls the newest images from ghcr.io and restarts what changed.
set -euo pipefail

IP="${1:?usage: deploy.sh <public-ip>}"
cd ~/examprep
COMPOSE="sudo docker compose -f docker-compose.prod.yml"

if [ ! -f .env ]; then
  echo "==> First deploy: generating secrets in ~/examprep/.env"
  hex() { openssl rand -hex "$1"; }
  b64() { openssl rand -base64 "$1" | tr -d '\n'; }
  ADMIN_PASS="Adm-$(hex 6)7"
  umask 077
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%F). Keep this file private; it is never in git.
SITE_IP=$IP
SITE_HOST=${IP//./-}.sslip.io
IMAGE_PREFIX=ghcr.io/pushkarv143/exam_prep
IMAGE_TAG=latest

DB_PASSWORD=$(hex 16)
JWT_SECRET=$(b64 48)
MFA_ENCRYPTION_KEY=$(b64 32)
MINIO_USER=examprep
MINIO_PASSWORD=$(hex 16)

# Only used on the very first start, to create the admin account. Change it after logging in.
ADMIN_EMAIL=admin@examprep.local
ADMIN_INITIAL_PASSWORD=$ADMIN_PASS
MFA_ENFORCE_FOR_STAFF=true

MAX_TAB_SWITCHES=2
# No SMTP yet, so no e-mails (password reset needs this). Fill SMTP_* and set true later.
EMAIL_ENABLED=false
# MOCK lets anyone "pay" without money. Switch to RAZORPAY with real keys before selling.
PAYMENT_PROVIDER=MOCK
EOF
  echo "    Admin login: admin@examprep.local / $ADMIN_PASS"
fi

echo "==> Pulling images"
if ! $COMPOSE pull --quiet; then
  echo "ERROR: could not download an image (see the error above)."
  echo "       For ghcr.io images: check the 'Build images' GitHub Action finished and the"
  echo "       packages exam_prep-backend / exam_prep-frontend are Public."
  exit 2
fi

echo "==> Starting containers"
$COMPOSE up -d --remove-orphans

echo "==> Waiting for the backend to become healthy (first start can take a few minutes)"
for i in $(seq 1 60); do
  state=$(sudo docker inspect -f '{{.State.Health.Status}}' examprep-backend-1 2>/dev/null || echo starting)
  if [ "$state" = "healthy" ]; then echo "    backend is healthy"; break; fi
  if [ "$state" = "unhealthy" ]; then echo "    backend is UNHEALTHY; last log lines:"; sudo docker logs --tail 40 examprep-backend-1; break; fi
  sleep 10
done

$COMPOSE ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}'
sudo docker image prune -f >/dev/null
free -h | awk 'NR<=3'

HOST=$(grep '^SITE_HOST=' .env | cut -d= -f2)
echo
echo "Site: https://$HOST   (fallback: http://$IP)"
